#!/usr/bin/perl -w
# rename - Larry's filename fixer
# Reprinted since "https://docstore.mik.ua/orelly/perl/cookbook/ch09_10.htm#ch09-40514"
$op = shift or die "Usage: rename expr [files]\n";
chomp(@ARGV = <STDIN>) unless @ARGV;
for (@ARGV) {
    $was = $_;
    eval $op;
    die $@ if $@;
    rename($was,$_) unless $was eq $_;
}
